### ISSUE TITLE
[Suggestion] The ability to disable certain skills in the config

### ISSUE THREAD

**Issue by Math321** [BeetoGuy/LevelUp2#10]
There are 23 skills in this mod, ignoring the "_____ Specialization" skills. I'd like the ability to turn certain ones off in the config. For example, disabling Prospecting in a modpack that already has ore multiplication in it.

**Comment by BeetoGuy** [comment]
With the way skill progression works, it would be difficult to just flat disable them. I could have them not do anything if disabled, but you would still have to spend skill points for the next skill tier.

**Comment by Math321** [comment]
Even just that would be great! Would you be able to put something in the tooltip of the skill like "this skill's effect has been disabled"?

**Comment by BeetoGuy** [comment]
I think it would be easiest to put it in the description screen, but yeah.
