### ISSUE TITLE
Missing json files

### ISSUE THREAD

**Issue by sublok** [BeetoGuy/LevelUp2#12]
Missing...
combat_bonus.json, 
mining_bonus.json, 
craft_bonus.json 

on create in /config/levelup2/json/skills/{skill_name}

**Comment by BeetoGuy** [comment]
I ended up leaving those out of configurability, since they only really provide experience bonuses that don't break the game that much.

**Comment by nmarshall23** [comment]
I get NoSuchFileException for these files, can I safely create empty files? 

The error is not if a skill's hasExternalJson in loadFromJson: https://github.com/BeetoGuy/LevelUp2/blob/f5dd7135774a32b5e618286f8616e4f1bcf6767e/src/main/java/levelup2/skills/SkillRegistry.java#L366

**Comment by BeetoGuy** [comment]
The exception doesn't really affect anything, but I think a blank json file should silence it.

**Comment by nmarshall23** [comment]
It does. Thanks, I'm just trying to clean up my logs.

**Comment by LemADEC** [comment]
Could we please fix the console spam from this?

**Comment by alfuken** [comment]
@BeetoGuy I guess those files are already in the source code, added by c6493a22d5118aac1c979559c532bb2aea41c0a8 , why won't you compile it and release a mod jar with this fix?..

**Comment by BeetoGuy** [comment]
There are several factors that had me step away from modding for a while. I'm looking into adding a few things before pushing a new fix, now that I'm beginning to get back into the swing of things.
Edit: It seems the fix has been live on CurseForge for about a year.

**Comment by Rencer** [comment]
> Edit: It seems the fix has been live on CurseForge for about a year.

Where exactly is that fix?
Because I use the latest version of the mod (Level Up! 2-1.1.22-1.12 from May 27, 2018) and it still spamming the log with this message that those files are missing.
