### ISSUE TITLE
Server Crashes - Ticking Issues

### ISSUE THREAD

**Issue by D3nnis3n** [BeetoGuy/LevelUp2#17]
Hey, after a lot of search it seemed like i' finally confident, that your mod is causing the crashes that occur on my Server. I went through all logs and found that this Crash happend every week once or so:

> Time: 10/8/17 8:30 PM
> Description: Exception in server tick loop
> java.util.ConcurrentModificationException
> at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
> at java.util.ArrayList$Itr.next(ArrayList.java:851)
> at levelup2.skills.crafting.FurnaceEfficiencyBonus.doFurnaceTicks(FurnaceEfficiencyBonus.java:114)
> at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_957_FurnaceEfficiencyBonus_doFurnaceTicks_WorldTickEvent.invoke(.dynamic)
> at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
> at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:285)
> at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:750)
> at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
> at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
> at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
> at java.lang.Thread.run(Thread.java:748)

Since i installed Advanced Rocketry those occur much more frequently, e.g. every ten to twenty minutes. Also new crashes occur. All of them do no longer occur when i remove your mod and Keep Advanced Rocketry. When i remove Advanced Rocketry and Keep yours only the first Crash occurs, but only very rare.

Those are other crashes i get with your mod installed (i've got a _LOT_ more _DIFFERENT_ ones, they ever have to do something with ASM: blablabla, twenty mods listed or ticking things - but as they're not saved as Crash Report it's hard to save them, when i'm not in Server Shell exactly when those happen)

> Time: 10/8/17 8:55 PM
> Description: Exception in server tick loop
> java.util.ConcurrentModificationException
> at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
> at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
> at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:290)
> at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:777)
> at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
> at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
> at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
> at java.lang.Thread.run(Thread.java:748)
> 

> Time: 10/8/17 8:35 PM
> Description: Exception in server tick loop
> java.util.ConcurrentModificationException
> at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
> at java.util.HashMap$EntryIterator.next(HashMap.java:1471)
> at java.util.HashMap$EntryIterator.next(HashMap.java:1469)
> at java.util.HashMap.putMapEntries(HashMap.java:511)
> at java.util.HashMap.(HashMap.java:489)
> at mekanism.api.transmitters.TransmitterNetworkRegistry.assignOrphans(TransmitterNetworkRegistry.java:136)
> at mekanism.api.transmitters.TransmitterNetworkRegistry.tickEnd(TransmitterNetworkRegistry.java:101)
> at mekanism.api.transmitters.TransmitterNetworkRegistry.onTick(TransmitterNetworkRegistry.java:93)
> at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_666_TransmitterNetworkRegistry_onTick_ServerTickEvent.invoke(.dynamic)
> at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
> at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:264)
> at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:710)
> at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
> at java.lang.Thread.run(Thread.java:748)

They do not appear in the log as a Minecraft Crash Report, as of this in most cases no Crash Report is generated and this is everything that is in the console.

**Comment by D3nnis3n** [comment]
Oh, i saw you had an update yesterday which i installed. I'm also confident this did not occur before this update.

**Comment by BeetoGuy** [comment]
Can you roll back to the version before to verify? I don't think I touched the furnace tick capability.

**Comment by D3nnis3n** [comment]
I'll do.

**Comment by D3nnis3n** [comment]
Nope, this crash is not casued by your mod. Removing both your and AR mod made the crashes happen much less often, but still there. Some time after my post i got a crash that destroyed my world and seemed to be relating to Ecology Mod, which i then removed. Since then no crashes had happen at all, anymore. I don't know if it was just random it crashed a hell lot more with AR and your mod or what exactly the Problem is, but it's not yours. I'll Close this issue, beg for forgiveness (but it was fucking hard to even find traces to which mod could be causing this) and let here a link to my Ecology Mod Issue, just in case you're interested: https://github.com/Artem226/MinecraftEcologyMod/issues/11
