### ISSUE TITLE
Ore Chunk problems:

### ISSUE THREAD

**Issue by Math321** [BeetoGuy/LevelUp2#24]
There are several issues with the Ore Chunk system.

Copper and tin are the only non-vanilla ores that have ore chunks, according to JEI.

The following (incomplete) list of ores will drop two blocks of ore when the Prospecting skill procs. These blocks of ore can then be placed and doubled AGAIN if the Prospecting skill procs again, and so on, ad infinitum.
Immersive Engineering nickel ore
Immersive Engineering silver ore
Immersive Enginnering lead ore
Immersive Engineering bauxite ore (AKA aluminium ore)
Immersive Engineering uranium ore

The following (also incomplete) list of ores are not affected by the Prospecting skill at all.
Embers nickel ore
Embers silver ore
Embers lead ore
Embers aluminum ore

Copper ore seems to function as intended (tested with both Embers and Immersive Engineering copper ore) - it will be made into ore chunks, and these ore chunks will be treated as ore for the purposes of further ore processing (tested with Embers' melter+stamper).

Tin ore will likewise be made into ore chunks (tested with both Embers and Immersive Engineering tin ore), but the tin ore chunks are not given an ore dictionary tag of oreTin, so they CANNOT be treated as ore for the purposes of further ore processing (tested with Embers' melter+stamper) - they can only be smelted into tin ingots directly.

Vanilla ore seems to work as intended (tested with gold ore and iron ore).

**Comment by BeetoGuy** [comment]
IE ores can drop chunks if you assign the OreDict name and a color through the config. I might revisit how this works at some point, but I need to learn a bit more about json file crawling. The latter, I'm wondering if it's a load order issue. I might just move all that stuff to PostInit instead of going through normal registration.

**Comment by Math321** [comment]
A friend reminded me to include the mod version in the issue: Level Up! 2-1.1.10-1.12
