### ISSUE TITLE
[1.12.2] [1.1.10] Furnace Efficiency Concurrent Modification Exception

### ISSUE THREAD

**Issue by Alaberti** [BeetoGuy/LevelUp2#25]
https://pastebin.com/zTkuhAbx

I have no idea what happened, but it crash-loops the server.

**Comment by Alaberti** [comment]
I still see the error in the console, but it is no longer crashing the server.

**Comment by BeetoGuy** [comment]
Yeah, that's unfortunately the best I can do. Something must be messing with the furnaces or brewing stands at the same time.
