### ISSUE TITLE
XP Levels not consumed properly.

### ISSUE THREAD

**Issue by loudwhitenoise** [BeetoGuy/LevelUp2#30]
I assigned levels to skill, then updated my xp amount (I used tome of knowledge from Thermal Foundation). Skill remains upgraded but XP returns to previous level. However does not appear to be on side of tome of knowledge, as the tome works fine with other level consumers like enchantments. I don't know if it only reacts this way to this one item, but dunno what else to test it with.

https://youtu.be/5L34NMgFJiI
I'm not good at making videos but this should be a reasonable demonstration.

**Comment by BeetoGuy** [comment]
Looking on Thermal Foundation's tracker, it seems like it's a common issue for anything that consumes levels. It may not be on our end and even has the potential of just being a vanilla bug.

**Comment by loudwhitenoise** [comment]
Alright, I'll bounce it over to them. Cheers!
