### ISSUE TITLE
Mod does not seem active- Java missing file errors on startup.

### ISSUE THREAD

**Issue by notmateo** [BeetoGuy/LevelUp2#37]
I'm trying to use this mod for a server, but when I start the server 3 files say they're not found- I went to the config folder and the files it was looking for wasn't there. Seems to be keeping the entire mod from working- none of the items or features are showing up.

https://pastebin.com/fxiK3WmE

**Comment by BeetoGuy** [comment]
It should work despite those files being missing. Just in case it is messing things up, the next update will have some blank dummy files, since those skills aren't intended to be configurable.

**Comment by notmateo** [comment]
Huh...

Yeah I'm definitely not seeing any additions to the server. I'll have to reinstall the mod and check the console a little closer, but I definitely remember this being the only thing I _saw_ in the console. I'll get back to you with a fuller console pastebin.

**Comment by BeetoGuy** [comment]
If it fails, try creating the respective missing json files in the directories and see if it works.
