### ISSUE TITLE
Progress Loss on Death

### ISSUE THREAD

**Issue by andr9528** [BeetoGuy/LevelUp2#41]
When i die all my progress is lost, which is a lot of levels wasted, if the loss of progress is intended then it is working as intended, but In in my world if have KeepInventory set to true, so it would be nice if that gamerule or a gamerule specific for LevelUp would make the player keep the progress through death.

Minecraft 1.12.2
Forge 14.23.2.2653
LevelUp! 2-1.1.19-1.12

**Comment by BeetoGuy** [comment]
There's a config option that can change that behavior.

**Comment by andr9528** [comment]
Great, now it just needs to be changeable from the Mod options menu but still thx alot for the heads up :)
