### ISSUE TITLE
Level reset when die

### ISSUE THREAD

**Issue by handi7a** [BeetoGuy/LevelUp2#43]
hi...
i have been using your mod for awhile, that I found when you die you lost your already gotten skill...
so after I die I have to choose again 3 perks(Mining, Crafting, Combat) and all skill that I already allocated is gone....  I dont know if there's config for this, but this is really a problem for me....
pls fix...
thx before...

**Comment by BeetoGuy** [comment]
There is a config option, called "Reset class on death," that will disable that behavior.

**Comment by handi7a** [comment]
Thanks!!
