### ISSUE TITLE
mod interaction with Biomes o plenty (not dynamic trees)

### ISSUE THREAD

**Issue by SciMuse** [BeetoGuy/LevelUp2#46]
when using dynamic trees with the dynamic trees bop addon and bop, the game will not load with levelup legacy for 1.12.2. The logs don't show anything nor does the console. I am using a bunch of mods and levelup legacy worked fine till loading dynamic trees. My wild guess is it has something to do with both mods affecting drops. Doesn't make sense though.

**Comment by SciMuse** [comment]
i had some time to test. Level up legacy is hanging on biomes a plenty. not dynamic trees.

**Comment by BeetoGuy** [comment]
Is there a crashlog I can reference?

**Comment by SciMuse** [comment]
there is no crashing or crash log. nothing shows in mc or forge logs or the console. it just hangs. and stays that way. i have to shut things down with task manager. for the testing i did, i started a new pack that had forge, nei, levelup legacy and the newest biomes o plenty. nothing else.

**Comment by BeetoGuy** [comment]
Looking through the logs with some debugger lines, it looks like it's hanging in the Ore Dictionary lookup code for the lumber bonus. I'll have to see how to remedy that.

**Comment by BeetoGuy** [comment]
It loads now, will upload the fix to CurseForge.
