### ISSUE TITLE
Please consider separate curse pages for LevelUp2 vs Legacy

### ISSUE THREAD

**Issue by C0rn3j** [BeetoGuy/LevelUp2#47]
https://minecraft.curseforge.com/projects/level-up/files

At the moment you post both Legacy and the reworked version on the same page. 

This breaks my updater script for one, and I imagine it casues some ruckus in the official Curse app too.

```
  Found newer mod: level-up
          Removed: Level Up! 2-1.1.19-1.12.jar
       Downloaded: Level Up! Legacy-0.15.1-1.12.2.jar
```

**Comment by BeetoGuy** [comment]
I thought this problem would pop up eventually. I'll go ahead and get that sorted.

**Comment by BeetoGuy** [comment]
Whenever CurseForge approves Legacy's page, it's done.
