### ISSUE TITLE
Crash on Server

### ISSUE THREAD

**Issue by D3nnis3n** [BeetoGuy/LevelUp2#48]
See the crashlog:
https://gist.github.com/D3nnis3n/d41de480972415efd1e41567243087ca

**Comment by BeetoGuy** [comment]
I might have done synchronization wrong, will upload a potential fix after I check a few things.

**Comment by D3nnis3n** [comment]
If the last update was supposed to fix this - it didn't.
https://gist.github.com/D3nnis3n/58e01b38e004d96f3882652e3d70f9fd

**Comment by BeetoGuy** [comment]
I'll just have to catch the CME again, I have no idea where this exception is coming from.
