### ISSUE TITLE
Ore generated from the bonus ore passive doesnt stack with vanilla items

### ISSUE THREAD

**Issue by Asmidus** [BeetoGuy/LevelUp2#61]
So far I've only seen this happen with iron but it might happen with other smeltables like gold too. The block of iron you get doesn't stack with the vanilla blocks because it has a tag on it.

**Comment by Asmidus** [comment]
It does in fact happen with gold as well. Ores that dont drop blocks such as coal, redstone, diamond, etc. I assume the tag is there to prevent the player from getting XP from smelting the ore but it's frustrating to deal with the stacks. If the extra XP is that bad maybe consider having it just drop iron bars or something instead?

**Comment by BeetoGuy** [comment]
The tag's there to prevent infinite duplication through re-placing ore blocks. I'm working on reworking the ore chunks config to make it more simple to add on to the list, so this probably won't be an issue in the next update.
