### ISSUE TITLE
infinite XP bug with mining specialization and ores

### ISSUE THREAD

**Issue by Shivaxi** [BeetoGuy/LevelUp2#62]
So essentially, you get XP from mining ores, you can place down ores like iron ore and mine it over and over again, giving infinite XP

I know there's an option for this called:      B:"Always drop ore chunks"=true

However silk touch overrides this on redstone, so you can still get infinite XP with a silk touch pick on redstone.

Was wondering if there'd be a way maybe just to not allow players to place ore blocks instead or something.

**Comment by BeetoGuy** [comment]
There is a way already implemented, but it's not foolproof. I'm working on trying to fix this in a more permanent manner.
