### ISSUE TITLE
Game doesn't recognize my levels & I'm unable to level up

### ISSUE THREAD

**Issue by kaporli** [BeetoGuy/LevelUp2#66]
I don't know if I'm doing something wrong or not. Level up is turned on but whenever I open the skill book no skill points are shown as available. Also, I don't know if this is still the case but from what I've seen on youtube your exp bar should notify you when you have another level up available, it might have changed since then? Any help would be appreciated

My forge version is 14.23.5.2847

Playing on 1.12.2

**Comment by BeetoGuy** [comment]
The leveling system has been changed entirely. You need to shift-right-click the book to exchange 5 levels for a skill point.
