### ISSUE TITLE
Compatibility Requests

### ISSUE THREAD

**Issue by Timeslice42** [BeetoGuy/LevelUp2#70]
The crafting specialization does not work with the FastWorkbech mod, nor the Actually Additions Crafting Table on a Stick.

It would also be nice if we could claim FastFurnace furnaces, since they are just vanilla furnaces with better caching.

**Comment by Timeslice42** [comment]
Okay, it seems that *some* recipes give XP in the Crafting Table on a stick, but not others.

**Comment by BeetoGuy** [comment]
It should work with anything that fires the crafting event. As for FastFurnace, it works with that as of latest.

**Comment by Timeslice42** [comment]
Thanks! I'll update my pack then.
