### ISSUE TITLE
[Suggestion] Availability to specify the amount of the furnace output of custom ore chunks in the config

### ISSUE THREAD

**Issue by ChromaPIE** [BeetoGuy/LevelUp2#72]
As for many tech mods, directly processing the ore blocks in the furnace doesn't always output a single piece of the product, the output may be **4** nuggets, or **2** piles of dust etc. As the chunks customized in the config have exactly the same oredicts as the ore blocks', if the output in the furnace could be customized too, it would be much more harmonious and it would be more friendly for modpacker willing to put this fantastic mod into their modpacks, without struggling with the complicated and repeated scripts. Think about how many kinds of ores are there in GTCE xd.

**Comment by BeetoGuy** [comment]
Untested for now since I'm pressed for time, but it'll be in the next release.
