### ISSUE TITLE
[Crash]Crash with 1.3.0-shaded

### ISSUE THREAD

**Issue by ChromaPIE** [BeetoGuy/LevelUp2#73]
Just now I have updated four mods including Thermal Foundation, Thermal Expansion, Tinker's Construct, and, of course, LevelUp2 to their latest release. But what is funny is that when launching the game, **Deep Mob Learning** gave a failure when constructing. Firstly I tried to revert TiC, TF and TE but DML still failed to be constructed and the crash report looks all the same. Despairly I tried to revert LevelUp2 to 1.2.6 and the game successfully launched. I'll put the crash reports below and it's a bit abnormal that it generates two reports at a time.

https://paste.dimdev.org/radazikoza.rb
https://paste.dimdev.org/reporomaru.rb

Thank you very much.

**Comment by BeetoGuy** [comment]
That's a bit of an odd crash, since the deobfuscated name for the one not being found is EnumFacing. I'm not 100% sure how that's happening.

**Comment by BeetoGuy** [comment]
Just on a whim, does it happen with FastFurnace uninstalled? It might be that compatibility mixin.

**Comment by ChromaPIE** [comment]
Removed FastFurnace and tried to launch it. Crash still happened and the report looks the same.

**Comment by BeetoGuy** [comment]
I'm unable to reproduce on a fresh instance. You might need to reinstall Forge.

**Comment by ChromaPIE** [comment]
Alright, I'll try later.

**Comment by ChromaPIE** [comment]
Just successfully lauched the game with the brand new 1.4.0. Thanks a lot.
