### ISSUE TITLE
Problem with displayed names of custom ore chunks 

### ISSUE THREAD

**Issue by ChromaPIE** [BeetoGuy/LevelUp2#75]
### First here is a screenshot.

https://imgur.com/a/yIgg9js

What I was pointing is a custom chunk for <<ore:oreRutile>> from GTCE, but as can be seen in the picture its name displayed incorrectly, so I have to add an extra tooltip to help myself to distinguish them.

### Then here is my config.

https://paste.dimdev.org/zenajunehe.bash

In these chunks, only the names of the following chunks displays correctly:

> **Coal**, **Diamond**, **Emerald**, **Redstone**, **Lapis**, **Nether Quartz**, **Mithril** (From Thermal Foundation, displayed as _Mana Infused Ore Chunk_), **Thorium** (From GTCE. NuclearCraft also exists BTW), **Certus Quartz** (From GTCE. Applied Energistics 2 also exists BTW).

Besides all of the chunks' name is **_tile.ore_block.name Chunk_**.

And by the way I am wondering how the mechanics of the furnacebonus upgrade, does it doubles everything that can be processed in the furnace? or does it depend on Ore Dictionary? If so, does it only double <<ore:ore*>>? And if so can the inputs that can be doubled with this upgrade configurable with both IItemStack and IOreDict available to be configured in the future?

**Comment by BeetoGuy** [comment]
I have no idea how GTCE's ore item classification works, so I'm just going to make the ore chunk name a config thing.

**Comment by ChromaPIE** [comment]
That will be just amazing. And by the way would you please check the additional question above? Appreciate that.

**Comment by BeetoGuy** [comment]
It doubles anything that wasn't specifically blacklisted, such as things with dust as an input. I don't really have plans for CraftTweaker support.
