### ISSUE TITLE
Silk Touch + Prospecting = Ore Dupe

### ISSUE THREAD

**Issue by TheFlash787** [BeetoGuy/LevelUp2#79]
**Version:** levelup2-1.2.4 (1.12.2)

Hey!

So we've found a bug, where when a player is using a pickaxe with Silk Touch, and has the prospecting skill enabled, ores are dupable. Let's use Diamond Ore as an example:

When a player breaks Diamond Ore, the prospecting skill is overriden and Diamond Ore is dropped, instead of Diamond Ore Chunks. 

However, since Prospecting also gives the ore a 5% chance of dropping added with each level of the skill, there's a chance that there'll be a second drop, which happens to be the ore block, and not the ore chunk. 

This means that players can continually break ore blocks with the skill, to gain a second block, which they can repeat and repeat until they have as many as they need. 

However, this doesn't seem to happen with Redstone Ore - It drops the chunks, instead of the ore blocks.

Thank you!

**Comment by BeetoGuy** [comment]
Seems to work properly as of latest (1.4.2)
