### ISSUE TITLE
prospecting issue

### ISSUE THREAD

**Issue by ZooLeeichi** [BeetoGuy/LevelUp2#80]
Hi!

I've tried messing around with the orelist the prospecting uses, and I have a suggestion, and found an issue.
As for suggestion, the mod seems to be using the part defined in the "ore name" for the drop when the ore is broken, not for the broken block, meaning that for ores that don't drop themselves, and the drop doesn't have an oredictionary(Coal), can only be prospected, if you have silk touch on the pickaxe, and also if you prospect redstone dust or lapis lazuli like this, I only get 2 chunks, which smelts for 1 piece each, meaning that I get consistently less value from these.

The issue(actually don't know if it's a bug in minecraft or the mod) I found is that if things are differentiated with only number at the end of the ID(silentgems:gem:30, minecraft:dye:4[lapis lazuli]), the mod sees them as the variant without those numbers(silentgems:gem instead of the gem:30, minecraft dye[ink sac] instead of dye:4).
The reason why I'm unsure whether the root of this is in the mod or mc itself, is because the give command doesn't recognise the numbered ID-s, and when I try to give myself minecraft:dye:4 with command, it sais that there's no such item, so if your mod uses the minecraft command, that might cause this.
additional info regarding this: I used a really old version of this mod(1.2.4) up to around an hour ago, and even though the command still doesn't seem to be able to recognise minecraft:dye:4 as an existing item, that version of the mod was able to handle the 48 gems of silentgems

**Comment by BeetoGuy** [comment]
/give uses a different format than the configs. The config uses a format similar to CraftTweaker. As for the non-standard drops not doubling under prospecting's effect, that's something I forgot to keep when I was reformatting how prospecting worked.
