### ISSUE TITLE
Extra chunks smelting into wrong things?

### ISSUE THREAD

**Issue by jengeld4** [BeetoGuy/LevelUp2#82]
Below is the part of the config that seems to be auto generated. Any non-vanilla ore chunk smelts into pulverized iron, and only the iron. Also the lapis chunks seem to smelt into ink sacs. I read the config and it seems to be correctly listing the correct materials, but it seems like the metadata isn't used right?

    # Ores that split into chunks. (String build: Ore name, color, experience yield, smelting result (mod:item:metadata:stacksize), chunk name, (optional) defined chunk [default: [oreCoal,0x343434,1,minecraft:coal,Coal], [oreIron,0xBC9980,1,minecraft:iron_ingot,Iron], [oreGold,0xFCEE4B,2,minecraft:gold_ingot,Gold], [oreDiamond,0x5DECF5,4,minecraft:diamond,Diamond], [oreEmerald,0x17DD62,4,minecraft:emerald,Emerald], [oreRedstone,0xFF0000,2,minecraft:redstone,Redstone], [oreLapis,0x193CB4,2,minecraft:dye:4,Lapis], [oreCopper,0xFF6D11,1,thermalfoundation:material:128,Copper], [oreTin,0x8FB0CE,1,thermalfoundation:material:129,Tin], [oreSilver,0xA9CDDC,2,thermalfoundation:material:130,Silver], [oreLead,0x515C73,2,thermalfoundation:material:131,Lead], [oreAluminum,0xE2CEE1,2,thermalfoundation:material:132,Aluminum], [oreNickel,0xAAA37B,2,thermalfoundation:material:133,Nickel], [orePlatinum,0xA1DCFF,3,thermalfoundation:material:134,Platinum], [oreIridium,0xB7BFDC,4,thermalfoundation:material:135,Iridium], [oreMithril,0x64B9D8,4,thermalfoundation:material:136,Mana-Infused]]
    S:surfaceores <
        oreCoal,0x343434,1,minecraft:coal,Coal
        oreIron,0xBC9980,1,minecraft:iron_ingot,Iron
        oreGold,0xFCEE4B,2,minecraft:gold_ingot,Gold
        oreDiamond,0x5DECF5,4,minecraft:diamond,Diamond
        oreEmerald,0x17DD62,4,minecraft:emerald,Emerald
        oreRedstone,0xFF0000,2,minecraft:redstone,Redstone
        oreLapis,0x193CB4,2,minecraft:dye:4,Lapis
        oreCopper,0xFF6D11,1,thermalfoundation:material:128,Copper
        oreTin,0x8FB0CE,1,thermalfoundation:material:129,Tin
        oreSilver,0xA9CDDC,2,thermalfoundation:material:130,Silver
        oreLead,0x515C73,2,thermalfoundation:material:131,Lead
        oreAluminum,0xE2CEE1,2,thermalfoundation:material:132,Aluminum
        oreNickel,0xAAA37B,2,thermalfoundation:material:133,Nickel
        orePlatinum,0xA1DCFF,3,thermalfoundation:material:134,Platinum
        oreIridium,0xB7BFDC,4,thermalfoundation:material:135,Iridium
        oreMithril,0x64B9D8,4,thermalfoundation:material:136,Mana-Infused
     >
}

Version 1.4.2

**Comment by BeetoGuy** [comment]
I found the problem. A miscount was making the metadata return 0 no matter what.
