### ISSUE TITLE
Crash with 1.4.4

### ISSUE THREAD

**Issue by TheSnowyChickens** [BeetoGuy/LevelUp2#83]
Hi,
after updating to v1.4.4 I could not start my modpack anymore.

Forge: 14.23.5.2854
+ (plus) more mods are in the crash report

Edit: 1.4.4 work fine with just Cyclic / Agricraft / Infinity Lib / JEI / Phosphor / Opti

Crash: [crash-2020-06-18_18.52.31-client.txt](https://github.com/BeetoGuy/LevelUp2/files/4800025/crash-2020-06-18_18.52.31-client.txt)

Log: 
[2020-06-18-1.log](https://github.com/BeetoGuy/LevelUp2/files/4800035/2020-06-18-1.log)

**Comment by BeetoGuy** [comment]
It's saying a json file is malformed. Try deleting the loot table files and having them refresh.

**Comment by TheSnowyChickens** [comment]
Hmm, with 1.4.3 my custom added loot worked fine.

Okay, I remove my old ones and close this issue, because, as you say, it is not a bug from the version. :)

Pls have a look after closing @ this issue, maybe I have some questions about the custom loot.

**Comment by TheSnowyChickens** [comment]
Okay, is it possible that I can't use Metadata in the ID name ?

example: 
{
 "type": "item",
 "name": "minecraft:dye:15",
 "weight": 7
 "functions": [
 {
  "function": "set_count",
  "count": {
   "min": 2,
   "max": 4
   }
  }
 ]
}

**Comment by BeetoGuy** [comment]
Those are following the loot table format, so "name" would just be "minecraft:dye" and you set the metadata with the following in the "functions" section:
{
"function": "set_data",
"data": 15
}

**Comment by TheSnowyChickens** [comment]
Ahh okay, a classic issue. xd

Ty for the hint and I will change it^^
