### ISSUE TITLE
Change class

### ISSUE THREAD

**Issue by Kazuto** [BeetoGuy/LevelUp2#84]
I can't find anything regarding this but is it possible to change the class after selecting one? Do I have to delete a user config for it or the likes?

**Comment by BeetoGuy** [comment]
It's not possible, but you can gain the benefits of other class specs by spending 10 skill points on each.

**Comment by Kazuto** [comment]
Ah okay, so selecting a class just grants benefits on that class in the early game but later on you have all benefits if each class has 10 skill points. Do I understand correctly?

**Comment by BeetoGuy** [comment]
Yeah, that's pretty much it.
