### ISSUE TITLE
Outrageous and Permanent Speed when upgrading sprint speed to 10

### ISSUE THREAD

**Issue by ghost** [BeetoGuy/LevelUp2#86]
When i decrease the level it doesn't change the speed i travel about 4000 blocks if i accidentally walk and hold ctrl

There is no log that shows any error with the mod and it cannot be anything else in my modpack i can remember changing.
Mods:
  [📁] 1.12 (folder)
  [✔️] AdFinders-1.12.2-2.3.14.0-build.0501
  [✔️] AdLods-1.12.2-1.0.8.0-build.0504
  [✔️] animania-1.12.2-1.7.3
  [✔️] antiqueatlas-1.12.2-4.6.3
  [✔️] AutoRegLib-1.3-32
  [✔️] B3M-1.12.2-17
  [✔️] BattleTowers-1.12.2
  [✔️] Baubles-1.12-1.5.2
  [✔️] bettercaves-1.12.2-2.0.3
  [✔️] BetterCombat-1.12.2-1.5.6
  [✔️] BetterFoliage-MC1.12-2.3.1
  [✔️] BetterFps-1.4.8
  [✔️] Biome_Bundle_O_Plenty-1.12.2_v1.0
  [✔️] Biome_Bundle-1.12.2-v6.1
  [✔️] BiomesOPlenty-1.12.2-7.0.1.2441-universal
  [✔️] Born+In+A+Barn+V1.8-1.12-1.1
  [✔️] Bountiful+Baubles-1.12.2-0.1.6
  [✔️] Bountiful-2.2.2
  [✔️] Capsule-1.12.2-3.3.11
  [✔️] champions-1.12.2-1.0.11.8
  [✔️] Chisel-MC1.12.2-1.0.2.45
  [✔️] Clumps-3.1.2
  [✔️] comforts-1.12.2-1.4.1.2
  [✔️] Controlling-3.0.9
  [✔️] CTM-MC1.12.2-1.0.2.31
  [✔️] CustomMobSpawner-3.11.5
  [✔️] DefaultOptions_1.12.2-9.2.8
  [✔️] DimensionalDoors-1.12.2-3.1.2-UNOFFICIAL
  [✔️] DrZharksMoCreaturesMod-12.0.5
  [📁] dungeons2 (folder)
  [✔️] Dungeons2-mc1.12.2-f14.23.5.2768-v1.7.1
  [✔️] DungeonTactics-1.12.2-0.16.8
  [✔️] DynamicSurroundings-1.12.2-3.6.1.0
  [✔️] DynamicTrees-1.12.2-0.9.8
  [✔️] DynamicTreesBOP-1.12.2-1.4.1e
  [✔️] ElectroblobsWizardry-4.2.11-MC1.12.2
  [✔️] Erebus-1.0.31
  [✔️] Exotic+Birds+1.12.2-3.2.0
  [✔️] FancyBlockParticles-1.12.x-2.4.1
  [✔️] foamfix-0.10.10-1.12.2
  [✔️] ForgeEndertech-1.12.2-4.5.2.0-build.0459
  [✔️] Forgelin-1.8.4
  [✔️] ForgottenItems+MC1.12.2+v1.2.1
  [✔️] FTBLib-5.4.7.2
  [✔️] FTBUtilities-5.4.1.129
  [✔️] GottschCore-mc1.12.2-f14.23.5.2768-v1.13.1
  [✔️] HardcoreDarkness-MC1.12.2-2.0
  [✔️] Hats-1.12.2-7.1.1
  [✔️] iceandfire-1.9.1-1.12.2
  [✔️] iChunUtil-1.12.2-7.2.2
  [✔️] ImprovedBackpacks-1.12.2-1.5.0.0
  [✔️] InfernalMobs-1.12.2
  [✔️] InventoryTweaks-1.63
  [✔️] ironchest-1.12.2-7.0.72.847
  [✔️] ironfurnaces-1.3.5
  [✔️] IvToolkit-1.3.3-1.12
  [✔️] jei_1.12.2-4.15.0.296
  [✔️] JustEnoughResources-1.12.2-0.9.2.60
  [✔️] levelup2-1.5.1
  [✔️] LibraryEx-1.12.2-1.1.3
  [✔️] llibrary-1.7.19-1.12.2
  [📁] memory_repo (folder)
  [✔️] MMDLib-1.12-1.0.0-rc2.36
  [✔️] MoBends_1.12.2-1.0.0-beta-20.06.20
  [✔️] MouseTweaks-2.10-mc1.12.2
  [✔️] mowziesmobs-1.5.6
  [✔️] mysticallib-1.12.2-1.7.0
  [✔️] mysticalworld-1.12.2-1.8.4
  [✔️] NetherEx-1.12.2-2.1.7
  [✔️] NetherMetals-1.12-1.2.0-rc2.76
  [✔️] NetherPortalFix_1.12.1-5.3.17
  [📁] OpenTerrainGenerator (folder)
  [✔️] OpenTerrainGenerator-1.12.2+-+v8.3
  [✔️] OptiFine_1.12.2_HD_U_F5
  [✔️] OreExcavation-1.4.150
  [✔️] OreLib-1.12.2-3.6.0.1
  [✔️] OreSpawn-1.12-3.3.1.179
  [✔️] overloadedarmorbar-1.0.4g
  [✔️] Patchouli-1.0-20
  [✔️] phosphor-1.12.2-0.2.6+build50-universal
  [✔️] QuarkOddities-1.12.2
  [✔️] Quark-r1.6-179
  [✔️] RealisticItemDrops-1.2.14
  [✔️] RecurrentComplex-1.4.8.2
  [✔️] Rex's-Additional-Structures-1.12.x-(v.2.3.1)
  [✔️] Roots-1.12.2-3.0.29
  [✔️] roughmobsrevamped-1.12.2-2.3.16
  [✔️] Ruins-1.12.2
  [✔️] savemystronghold-1.12.2-1.0.0
  [✔️] ShoulderSurfing-1.12.2-1.15.1
  [✔️] smallernp_1.12-1.1
  [✔️] SoundFilters-0.12_for_1.12
  [✔️] SpartanShields-1.12.2-1.5.4
  [✔️] SpartanWeaponry-1.12.2-beta-1.3.8
  [✔️] spectrite-1.7.1
  [✔️] Surge-1.12.2-2.0.77
  [✔️] tektopia-1.1.0
  [✔️] theoneprobe-1.12-1.4.28
  [✔️] Traverse-1.12.2-1.6.0-69
  [✔️] tschipplib-1.12.2-1.1.4
  [✔️] VanillaFix-1.0.10-150
  [✔️] Waystones_1.12.2-4.1.0
  [✔️] WizardAnimalsBeta1.0
  [✔️] xptome-1.12.2-v1.1.4

**Comment by BeetoGuy** [comment]
Yeah, that's a math error for sure.
