### ISSUE TITLE
Outrageous Speed when Sprinting is Max Level

### ISSUE THREAD

**Issue by Numeron202** [BeetoGuy/LevelUp2#90]
When I sprint I travel ridiculously fast with max level sprint. I also attempted to decrease the levels and that didn't help. This sounds like a very similar issue to #86 .

There is no log that shows any error with the mod and I have made no other direct changes to my modpack except for updating this mod. Attached is the list of mods that I currently use.

Thank you!

[mods.zip](https://github.com/BeetoGuy/LevelUp2/files/5114254/mods.zip)

**Comment by BeetoGuy** [comment]
Have you updated from below 1.5.0? You might need to delete the skill configs and let them regenerate.

**Comment by Numeron202** [comment]
Thank you
