### ISSUE TITLE
Dirt No Longer Dropping

### ISSUE THREAD

**Issue by Numeron202** [BeetoGuy/LevelUp2#91]
I receive the random loot table drops, but the dirt itself no longer drops with the latest update.

**Comment by BeetoGuy** [comment]
Have you updated from below 1.5.0? If so, you'll have to regenerate the skill files in the config folder.

**Comment by Numeron202** [comment]
Hmmm. I did regenerate all the files in the config folder (skills, classes and the loose config file) , but still having the same issue.

**Comment by BeetoGuy** [comment]
Looks to be working on my end as of latest.

**Comment by Numeron202** [comment]
Thank you. It seems to be something on my end. I will figure it out. Thank you for the time and consideration.
